project:
  name: quickstart-uipath-automation-suite
  parameters:
    QSS3KeyPrefix: "quickstart-uipath-automation-suite/"
    QSS3BucketName: "$[taskcat_autobucket]"
    QSS3BucketRegion: "$[taskcat_current_region]"
    HAAPassword: "$[taskcat_genpass_8]"
    OrchestratorPassword: "$[taskcat_genpass_8]"
    RDSUsername: "$[taskcat_random-string]"
    RDSPassword: "$[taskcat_genpass_8]"
    RDSDBName: "$[taskcat_random-string]"
    GatewayName: "$[taskcat_random-string]"
    HAAUser: admin@shivansh.dev
    HostedZoneID: Z03411186LX2V3ZE3N4K
    KeyPairName: sshvans
  regions:
  - ap-northeast-1
  - ap-northeast-2
  - ap-south-1
  - ap-east-1
  - ca-central-1
  - eu-central-1
  - eu-west-1
  - eu-west-2
  - eu-west-3
  - me-south-1
  - sa-east-1
  - us-east-1
  - us-east-2
  - us-west-1
  - us-west-2
  shorten_stack_name: true
  s3_regional_buckets: true
  package_lambda: false
  lambda_source_path: functions/source
  lambda_zip_path: functions/packages

tests:
  default-orchestrator:
    template: ./templates/main.template.yaml
    regions:
    - us-east-2
    parameters:
      AvailabilityZones: "$[taskcat_getaz_2]"
      UiPathFQDN: "$[taskcat_random-string].shivansh.dev"
      MultiNode: "Single Node"
      UseLevel7LoadBalancer: 'ALB'
      UiPathVersion: "2021.10.1"
      ServiceProfile: 'Default platform'
