AWSTemplateFormatVersion: 2010-09-09
Description: >-
  This template creates a Multi-AZ, multi-subnet VPC infrastructure with UIPath
  Automation Suite deployed in private subnets, with a Load Balancer behind Route 53 in
  public subnets.
Metadata:
  QuickStartDocumentation:
    EntrypointName: Launch into a new VPC
    Order: "1"
  'AWS::CloudFormation::Interface':
    ParameterGroups:
      - Label:
          default: Availability Zone configuration
        Parameters:
          - AvailabilityZones
          - NumberOfAZs
      - Label:
          default: Automation Suite instance configuration
        Parameters:
          - KeyPairName
      - Label:
          default: Automation Suite deployment configuration
        Parameters:
          - MultiNode
          - UseLevel7LoadBalancer
          - UiPathVersion
      - Label:
          default: Automation Suite services
        Parameters:
          - ActionCenter
          - AutomationHub
          - AutomationOps
          - Insights
          - TestManager
          - AiCenter
          - BusinessApps
          - DocumentUnderstanding
          - TaskMining
          - AddGpu
      - Label:
          default: DNS or SSL configuration
        Parameters:
          - UiPathFQDN
          - HostedZoneID
      - Label:
          default: RDS configuration
        Parameters:
          - RDSEngine
          - RDSVersion
      - Label:
          default: Quick Start S3 bucket configuration
        Parameters:
          - QSS3BucketName
          - QSS3KeyPrefix
          - QSS3BucketRegion
    ParameterLabels:
      AvailabilityZones:
        default: Availability Zones
      NumberOfAZs:
        default: Number of Availability Zones
      KeyPairName:
        default: Instance key pair
      MultiNode:
        default: Deployment type
      UseLevel7LoadBalancer:
        default: Load Balancer
      UiPathVersion:
        default: Automation Suite version
      ActionCenter:
        default: Action Center
      AutomationHub:
        default: Automation Hub
      AutomationOps:
        default: Automation Ops
      Insights:
        default: Insights
      TestManager:
        default: Test Manager
      AiCenter:
        default: AI Center
      BusinessApps:
        default: Apps
      DocumentUnderstanding:
        default: Document Understanding
      TaskMining:
        default: Task Mining
      AddGpu:
        default: Add GPU enabled VMs
      UiPathFQDN:
        default: Hosting FQDN
      HostedZoneID:
        default: ID of Route 53 hosted zone
      RDSEngine:
        default: Engine of SQL Server deployed on RDS
      RDSVersion:
        default: Verions of SQL Server deployed on RDS
      QSS3BucketName:
        default: Template-hosting S3 bucket
      QSS3KeyPrefix:
        default: Template folder
      QSS3BucketRegion:
        default: Template-hosting S3 region
Parameters:
  AvailabilityZones:
    Description: >-
      Choose up to three Availability Zones to use for the VPC subnets.
    Type: "List<AWS::EC2::AvailabilityZone::Name>"
  NumberOfAZs:
    AllowedValues:
      - '2'
      - '3'
    Default: '2'
    Description: >-
      Choose the number of Availability Zones to use in the VPC. This must match the number of AZs selected in the *Availability Zones* parameter.
    Type: String
  KeyPairName:
    Description: Existing key pair to connect to virtual machine (VM) instances.
    Type: 'AWS::EC2::KeyPair::KeyName'
  MultiNode:
    Description: Install Automation Suite on a Single Node (recommended for evaluation/dev purposes) or Multi-node (recommended for production purposes)
    Type: String
    Default: 'Single Node'
    AllowedValues:
      - "Single Node"
      - "Multi Node"
  UseLevel7LoadBalancer:
    Description: Select either an Application Load Balancer (ALB) or a Network Load Balancer (NLB)
    Type: String
    Default: 'ALB'
    AllowedValues:
      - 'ALB'
      - 'NLB'
  UiPathVersion:
    Description: UiPath version to install
    Type: String
    Default: '2021.10.1'
    AllowedValues:
      - '2021.10.0'
      - '2021.10.1'
  ActionCenter:
    Description: Choose false to disable Action Center installation.
    Type: String
    Default: 'true'
    AllowedValues:
      - 'true'
      - 'false'
  Insights:
    Description: Choose false to disable Insights installation.
    Type: String
    Default: 'true'
    AllowedValues:
      - 'true'
      - 'false'
  AutomationHub:
    Description: Choose false to disable Automation Hub installation.
    Type: String
    Default: 'true'
    AllowedValues:
      - 'true'
      - 'false'
  AutomationOps:
    Description: Choose false to disable Automation Ops installation.
    Type: String
    Default: 'true'
    AllowedValues:
      - 'true'
      - 'false'
  TestManager:
    Description: Choose false to disable Test Manager installation.
    Type: String
    Default: 'true'
    AllowedValues:
      - 'true'
      - 'false'
  AiCenter:
    Description: Choose false to disable AI Center installation.
    Type: String
    Default: 'true'
    AllowedValues:
      - 'true'
      - 'false'
  BusinessApps:
    Description: Choose false to disable Apps installation.
    Type: String
    Default: 'true'
    AllowedValues:
      - 'true'
      - 'false'
  DocumentUnderstanding:
    Description: Choose false to disable Document Understanding installation.
    Type: String
    Default: 'true'
    AllowedValues:
      - 'true'
      - 'false'
  TaskMining:
    Description: Choose false to disable Task Mining installation.
    Type: String
    Default: 'true'
    AllowedValues:
      - 'true'
      - 'false'
  AddGpu:
    Description: >-
      Choose true to add a GPU enabled VM to the deployment.
    Type: String
    Default: 'false'
    AllowedValues:
      - 'true'
      - 'false'
  HostedZoneID:
    Description: ID of Route 53 hosted zone.
    Type: AWS::Route53::HostedZone::Id
  UiPathFQDN:
    Description: >-
      Fully qualified domain name (FQDN) for Automation Suite.
      This must be either a subdomain, or root domain, of the of ID of Route 53 hosted zone parameter.
    Type: String
    AllowedPattern: '(?=^.{4,253}$)(^((?!-)[a-zA-Z0-9-]{0,62}[a-zA-Z0-9]\.)+[a-zA-Z]{2,63}$)'
    ConstraintDescription: >-
      Fully qualified domain names can include numbers, lowercase letters, uppercase letters and hyphens (-).
  RDSEngine:
    Type: String
    Description: RDS MS SQL engine
    Default: "sqlserver-se"
    AllowedValues:
      - "sqlserver-ee"
      - "sqlserver-se"
      - "sqlserver-web"
  RDSVersion:
    Type: String
    Description: RDS MS SQL version
    Default: "15.00"
    AllowedValues:
      - "15.00"
      - "14.00"
      - "13.00"
  QSS3BucketName:
    AllowedPattern: '^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$'
    ConstraintDescription: >-
      Quick Start bucket name can include numbers, lowercase letters, uppercase
      letters, and hyphens (-). It cannot start or end with a hyphen (-).
    Description: Name of the S3 bucket for your copy of the Quick Start assets. Do not modify.
    Type: String
    Default: uipath-s3-quickstart
  QSS3BucketRegion:
    Default: us-east-1
    Description: >-
       AWS Region where the Quick Start S3 bucket (QSS3BucketName) is hosted. Do not modify.
    Type: String
    AllowedPattern: (us(-gov)?|ap|ca|cn|eu|sa)-(central|(north|south)?(east|west)?)-\d
    ConstraintDescription: Must be a valid AWS Region code.
  QSS3KeyPrefix:
    AllowedPattern: '^[0-9a-zA-Z-/]*/$'
    ConstraintDescription: >-
      The Quick Start S3 key prefix can include numbers, lowercase letters,
      uppercase letters, hyphens (-), and forward slashes (/).
    Default: aws-quickstart-sf/
    Description: >-
      S3 key prefix that is used to simulate a directory for your copy of the
      Quick Start assets. Do not modify.
    Type: String
Conditions:
  UsingDefaultBucket: !Equals
    - !Ref QSS3BucketName
    - uipath-s3-quickstart
  3AZCondition: !Equals
    - !Ref NumberOfAZs
    - '3'
Resources:
  NetworkStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: !Sub
        - >-
          https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}submodules/quickstart-aws-vpc/templates/aws-vpc.template.yaml
        - S3Bucket: !If
            - UsingDefaultBucket
            - !Sub '${QSS3BucketName}-${AWS::Region}'
            - !Ref QSS3BucketName
          S3Region: !If
            - UsingDefaultBucket
            - !Ref 'AWS::Region'
            - !Ref QSS3BucketRegion
      Parameters:
        AvailabilityZones: !Join
          - ','
          - !Ref AvailabilityZones
        NumberOfAZs: !Ref NumberOfAZs
        VPCCIDR: "10.0.0.0/16"
  ServiceFabricStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: !Sub
        - >-
          https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}templates/uipath-sf.template.yaml
        - S3Bucket: !If
            - UsingDefaultBucket
            - !Sub '${QSS3BucketName}-${AWS::Region}'
            - !Ref QSS3BucketName
          S3Region: !If
            - UsingDefaultBucket
            - !Ref 'AWS::Region'
            - !Ref QSS3BucketRegion
      Parameters:
        VPCCIDR: "10.0.0.0/16"
        VPCID: !GetAtt NetworkStack.Outputs.VPCID
        KeyPairName: !Ref KeyPairName
        PrivateSubnetIDs: !Join
          - ','
          - - !GetAtt NetworkStack.Outputs.PrivateSubnet1AID
            - !GetAtt NetworkStack.Outputs.PrivateSubnet2AID
            - !If [ 3AZCondition, !GetAtt NetworkStack.Outputs.PrivateSubnet3AID, !Ref "AWS::NoValue" ]
        PublicSubnetIDs: !Join
          - ','
          - - !GetAtt NetworkStack.Outputs.PublicSubnet1ID
            - !GetAtt NetworkStack.Outputs.PublicSubnet2ID
            - !If [ 3AZCondition, !GetAtt NetworkStack.Outputs.PublicSubnet3ID, !Ref "AWS::NoValue" ]
        MultiNode: !Ref MultiNode
        UseLevel7LoadBalancer: !Ref UseLevel7LoadBalancer
        PerformInstallation: "true"
        AddGpu: !Ref AddGpu
        UiPathFQDN: !Ref UiPathFQDN
        ActionCenter: !Ref ActionCenter
        AutomationHub: !Ref AutomationHub
        AutomationOps: !Ref AutomationOps
        Insights: !Ref Insights
        TestManager: !Ref TestManager
        AiCenter: !Ref AiCenter
        BusinessApps: !Ref BusinessApps
        DocumentUnderstanding: !Ref DocumentUnderstanding
        TaskMining: !Ref TaskMining
        HostedZoneID: !Ref HostedZoneID
        QSS3BucketName: !Ref QSS3BucketName
        QSS3KeyPrefix: !Ref QSS3KeyPrefix
        QSS3BucketRegion: !Ref QSS3BucketRegion
        UiPathVersion: !Ref UiPathVersion
        RDSEngine: !Ref RDSEngine
        RDSVersion: !Ref RDSVersion

Outputs:
  InterfaceTour:
    Value: "https://docs.uipath.com/automation-suite/docs/interface-tour"
    Description: |-
      The general-use Automation Suite user interface serves as a portal for both organization administrators and organization users.
      It is a common organization-level resource from where everyone can access all of your Automation Suite areas: administration pages,
      platform-level pages, service-specific pages, and user-specific pages.
  AutomationSuiteUrl:
    Description: Automation Suite Portal
    Value: !Sub "https://${UiPathFQDN}"
  AutomationSuiteSecret:
    Description: Credentials for Automation Suite Portal
    Value: !Join
      - ''
      - - !Sub "https://${AWS::Region}.console.aws.amazon.com/secretsmanager/home?region=${AWS::Region}#!/secret?name="
        - !GetAtt ServiceFabricStack.Outputs.OrgSecret
  HostAdministrationUrl:
    Description: |-
      The host portal is for system administrators to configure the Automation Suite instance.
      The settings that you configure from this portal are inherited by all your organizations, and some can be overwritten at the organization level.
    Value: !Sub "https://${UiPathFQDN}"
  HostAdministrationSecret:
    Description: Credentials for Host Administration
    Value: !Join
      - ''
      - - !Sub "https://${AWS::Region}.console.aws.amazon.com/secretsmanager/home?region=${AWS::Region}#!/secret?name="
        - !GetAtt ServiceFabricStack.Outputs.PlatformSecret
  ArgoCd:
    Description: |-
      You can use the ArgoCD console to manage installed products.
    Value: !Sub "https://alm.${UiPathFQDN}"
  ArgoCdSecret:
    Description: Secret storing the ArgoCD admin credentials
    Value: !Join
      - ''
      - - !Sub "https://${AWS::Region}.console.aws.amazon.com/secretsmanager/home?region=${AWS::Region}#!/secret?name="
        - !GetAtt ServiceFabricStack.Outputs.ArgoCdSecret
  MonitoringFqdn:
    Description: The Monitoring login page
    Value: !Sub "https://monitoring.${UiPathFQDN}"
  InputJsonSecret:
    Description: Secret storing the input.json content.
    Value: !Join
      - ''
      - - !Sub "https://${AWS::Region}.console.aws.amazon.com/secretsmanager/home?region=${AWS::Region}#!/secret?name="
        - !GetAtt ServiceFabricStack.Outputs.InputJsonSecret
